# Generated by Django 2.1.4 on 2019-01-30 20:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.CharField(default='text', max_length=60)),
                ('phone', models.IntegerField()),
                ('mail', models.EmailField(max_length=254)),
                ('message', models.TextField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(default='text', max_length=200)),
                ('project_main_image', models.FileField(blank=True, max_length=1000, null=True, upload_to='page/%Y/%m/%d')),
                ('project_description', models.TextField(default='text', max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='RelatedImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_image', models.FileField(blank=True, max_length=1000, null=True, upload_to='page/%Y/%m/%d')),
                ('description', models.TextField(default='text', max_length=5000)),
                ('projects', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='page.Projects')),
            ],
        ),
        migrations.RemoveField(
            model_name='comment',
            name='name',
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_name',
            field=models.CharField(default='text', max_length=50),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(default='text'),
        ),
    ]
