# Generated by Django 2.1.4 on 2019-01-30 23:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_auto_20190130_2037'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectWorkDone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(default='text', max_length=5000)),
                ('work', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='page.Projects')),
            ],
        ),
        migrations.RemoveField(
            model_name='relatedimages',
            name='description',
        ),
    ]
