# Generated by Django 2.1.4 on 2019-01-31 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0003_auto_20190130_2352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectworkdone',
            name='work',
        ),
        migrations.AddField(
            model_name='projects',
            name='project_description_details',
            field=models.TextField(default='text', max_length=5000),
        ),
        migrations.DeleteModel(
            name='ProjectWorkDone',
        ),
    ]
