# Generated by Django 2.1.4 on 2019-02-05 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0004_auto_20190131_1759'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opinion', models.FileField(blank=True, max_length=1000, null=True, upload_to='page/%Y/%m/%d')),
            ],
        ),
    ]
